### ISSUE TITLE
Wrong help directory in sclang-vars.el.in

### ISSUE THREAD

**Issue by apteryks** [widp/el-supercollider#1]
Hello,

Shouldn't the help directory in sclang-vars.el.in be ` @PKG_DATA_DIR@/HelpSource` instead of  `@PKG_DATA_DIR@/Help`? After installing SuperCollider I don't have "Help" but I do have "HelpSource" under share/SuperCollider.

**Comment by widp** [comment]
@Apteryks 
From what I see in the codebase, the help files are pointless as the functions that use them are either commented out or broken. 
This code has been unmaintained for quite some time, so feel free to suggest changes etc..

**Comment by apteryks** [comment]
I see! Thanks for the heads-up!

**Comment by widp** [comment]
I've updated the path.
